In [2]:
from backtesting import Backtest, Strategy
from backtesting.test import GOOG
import numpy as np
import pandas as pd
import os
import sys
import matplotlib.pyplot as plt
%matplotlib inline
sys.path.append(os.path.abspath(os.path.join('../scripts')))
# data=pd.read_csv('../data/MSFT.csv')

`add signal column randomly`

In [3]:
GOOG["Signal"] = np.random.randint(-1,2,len(GOOG))

print(GOOG)

              Open    High     Low   Close    Volume  Signal
2004-08-19  100.00  104.06   95.96  100.34  22351900      -1
2004-08-20  101.01  109.08  100.50  108.31  11428600       0
2004-08-23  110.75  113.48  109.05  109.40   9137200       1
2004-08-24  111.24  111.60  103.57  104.87   7631300       1
2004-08-25  104.96  108.00  103.88  106.00   4598900       0
...            ...     ...     ...     ...       ...     ...
2013-02-25  802.30  808.41  790.49  790.77   2303900       0
2013-02-26  795.00  795.95  784.40  790.13   2202500      -1
2013-02-27  794.80  804.75  791.11  799.78   2026100       0
2013-02-28  801.10  806.99  801.03  801.20   2265800      -1
2013-03-01  797.80  807.14  796.15  806.19   2175400       1

[2148 rows x 6 columns]

In [22]:
GOOG

              Open    High     Low   Close    Volume  Signal
2004-08-19  100.00  104.06   95.96  100.34  22351900      -1
2004-08-20  101.01  109.08  100.50  108.31  11428600      -1
2004-08-23  110.75  113.48  109.05  109.40   9137200       1
2004-08-24  111.24  111.60  103.57  104.87   7631300       0
2004-08-25  104.96  108.00  103.88  106.00   4598900       1
...            ...     ...     ...     ...       ...     ...
2013-02-25  802.30  808.41  790.49  790.77   2303900       0
2013-02-26  795.00  795.95  784.40  790.13   2202500      -1
2013-02-27  794.80  804.75  791.11  799.78   2026100       0
2013-02-28  801.10  806.99  801.03  801.20   2265800       1
2013-03-01  797.80  807.14  796.15  806.19   2175400      -1

[2148 rows x 6 columns]

In [19]:
sys.path.append(os.path.abspath(os.path.join('../scripts')))
data=pd.read_csv('../data/MSFT.csv')

In [23]:
data

,Date,Open,High,Low,Close,Adj Close,Volume
0,1986-03-13 00:00:00-05:00,0.088542,0.101563,0.088542,0.097222,0.060980,1031788800
1,1986-03-14 00:00:00-05:00,0.097222,0.102431,0.097222,0.100694,0.063158,308160000
2,1986-03-17 00:00:00-05:00,0.100694,0.103299,0.100694,0.102431,0.064247,133171200
3,1986-03-18 00:00:00-05:00,0.102431,0.103299,0.098958,0.099826,0.062613,67766400
4,1986-03-19 00:00:00-05:00,0.099826,0.100694,0.097222,0.098090,0.061524,47894400
...,...,...,...,...,...,...,...
9216,2022-10-05 00:00:00-04:00,245.990005,250.580002,244.100006,249.199997,249.199997,20347100
9217,2022-10-06 00:00:00-04:00,247.929993,250.339996,246.080002,246.789993,246.789993,20239900
9218,2022-10-07 00:00:00-04:00,240.899994,241.320007,233.169998,234.240005,234.240005,37732400
9219,2022-10-10 00:00:00-04:00,233.050003,234.559998,226.729996,229.250000,229.250000,29726900
9220,2022-10-11 00:00:00-04:00,227.619995,229.059998,224.490005,224.970001,224.970001,19977846

`Desing a strategy where  we use a Signal value of 1 to mean buy, -1 to mean we sell, and 0 we will  do nothing.
    `

In [3]:
class SignalStrategy(Strategy):
    '''
    use a Signal value of 1 to mean buy, -1 is sell, 
    and 0 is do nothing.
    '''
    def init(self):
        pass

    def next(self):
        current_signal= self.data.Signal[-1]
        if current_signal == 1:
            if not self.position:
                self.buy()
        elif current_signal == -1:
            if self.position:
                self.position.close()

In [4]:
bt = Backtest(GOOG, SignalStrategy, cash=10_000)

`print the statistics`

In [5]:
stats = bt.run()
print(stats)

Start                     2004-08-19 00:00:00
End                       2013-03-01 00:00:00
Duration                   3116 days 00:00:00
Exposure Time [%]                   68.808194
Equity Final [$]                      23624.9
Equity Peak [$]                      24099.05
Return [%]                            136.249
Buy & Hold Return [%]              703.458242
Return (Ann.) [%]                   10.612239
Volatility (Ann.) [%]               28.390237
Sharpe Ratio                         0.373799
Sortino Ratio                        0.639063
Calmar Ratio                         0.216798
Max. Drawdown [%]                  -48.949894
Avg. Drawdown [%]                   -5.277813
Max. Drawdown Duration     1922 days 00:00:00
Avg. Drawdown Duration       91 days 00:00:00
# Trades                                  376
Win Rate [%]                        52.393617
Best Trade [%]                      29.550293
Worst Trade [%]                    -11.821235
Avg. Trade [%]                       0.232734
Max. Trade Duration          27 days 00:00:00
Avg. Trade Duration           5 days 00:00:00
Profit Factor                        1.268883
Expectancy [%]                       0.310119
SQN                                    1.1608
_strategy                      SignalStrategy
_equity_curve                           Eq...
_trades                        Size  Entry...
dtype: object

In [26]:
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')
bt.plot()

Row(id='7527', ...)